include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_print
    - flutter_style_todos
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_pub_dependencies
    - use_is_even_rather_than_modulo
    - use_setters_to_change_properties

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/"
  errors:
    invalid_annotation_target: ignore


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options