name: starter
description: A Flutter Starter Project
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cherry_toast: ^1.0.8
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5

  dio: ^4.0.6

  fl_country_code_picker: ^0.0.4

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^7.7.0

  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^7.0.1

  form_builder_extra_fields: ^8.3.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.4.0
  freezed_annotation: ^2.2.0

  get_it: ^7.2.0
  go_router: ^6.0.5
  graphql: ^5.1.1
  graphql_flutter: ^5.1.0

  image_picker: ^0.8.6
  in_app_review: ^2.0.6
  intl: ^0.17.0

  logger: ^1.1.0

  rxdart: ^0.27.7

  shared_preferences: ^2.0.15
  stack_trace: ^1.10.0

  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0

  faker: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  freezed: ^2.2.0

  http_mock_adapter: ^0.3.3

  import_sorter: ^4.6.0
  intl_translation: ^0.18.0

  json_serializable: ^6.5.4

  mockito: ^5.3.2

  test: ^1.21.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env.development
    - env.production
    - env.staging

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: lib/assets/fonts/Schyler-Regular.ttf
  #       - asset: lib/assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: lib/assets/fonts/TrajanPro.ttf
  #       - asset: lib/assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
