name: starter
version: 0.0.1
summary: A Flutter Starter Project
description: A Flutter Starter Project

confinement: strict
base: core18
grade: stable

slots:
  starter:
    interface: dbus
    bus: session
    name: com.bilowapp.starter

apps:
  starter:
    command: starter
    extensions: [flutter-master]
    plugs:
      - network
    slots:
      - starter
parts:
  starter:
    source: .
    plugin: flutter
    flutter-target: lib/main_production.dart
