name: Deploy Web to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - name: Setup Flutter v3.3.10
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.3.10
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

#      - name: Test code
#        run: flutter test

#      - name: Analyze code
#        run: flutter analyze

      - name: Build web
        run: flutter build web --release --web-renderer html --base-href /Naruto/ -t lib/main_production.dart

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /Naruto/
          customArgs: -t lib/main_production.dart
